[package]
name = "proc_macro"
version = "0.1.0"
edition = "2024"

[features]
state = []

[lib]
proc-macro = true

[dependencies]
syn = { version = "2", features = ["full"] }
quote = "1"
proc-macro2 = "1"